/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zys_ndkdemo_MainActivity */

#ifndef _Included_com_zys_ndkdemo_MainActivity
#define _Included_com_zys_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zys_ndkdemo_MainActivity
 * Method:    native_Get_String
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zys_ndkdemo_MainActivity_native_1Get_1String
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
